/* tslint:disable */
/* eslint-disable */
/**
 * Tiny Chat Application
 * The Tiny Chat App API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface IChatDto
 */
export interface IChatDto {
    /**
     * Session id to keep conversation context in memory. If omitted, \"default\" is used.
     * @type {string}
     * @memberof IChatDto
     */
    'sessionId'?: string;
    /**
     * Message from the chat
     * @type {string}
     * @memberof IChatDto
     */
    'message': string;
    /**
     * Additional system instruction (optional).
     * @type {string}
     * @memberof IChatDto
     */
    'systemInstruction'?: string;
    /**
     * Enable/disable RAG from local files under ./rag (defaults from env AI_ENABLE_RAG).
     * @type {boolean}
     * @memberof IChatDto
     */
    'useRag'?: boolean;
    /**
     * Enable/disable web search (defaults from env AI_ENABLE_WEB_SEARCH).
     * @type {boolean}
     * @memberof IChatDto
     */
    'useWebSearch'?: boolean;
}
/**
 * 
 * @export
 * @interface IChatResponse
 */
export interface IChatResponse {
    /**
     * Session id used for conversation memory.
     * @type {string}
     * @memberof IChatResponse
     */
    'sessionId'?: string;
    /**
     * Model used to generate the reply (when AI is enabled).
     * @type {string}
     * @memberof IChatResponse
     */
    'model'?: string;
    /**
     * Reply from the server
     * @type {string}
     * @memberof IChatResponse
     */
    'reply': string;
    /**
     * Number of messages kept in memory for this session.
     * @type {number}
     * @memberof IChatResponse
     */
    'messagesInMemory'?: number;
    /**
     * RAG sources used (if enabled and matched).
     * @type {Array<string>}
     * @memberof IChatResponse
     */
    'ragSources'?: Array<string>;
    /**
     * Web search sources used (if enabled).
     * @type {Array<string>}
     * @memberof IChatResponse
     */
    'webSources'?: Array<string>;
}
/**
 * 
 * @export
 * @interface IClearChatResponse
 */
export interface IClearChatResponse {
    /**
     * Session id that was requested to clear.
     * @type {string}
     * @memberof IClearChatResponse
     */
    'sessionId': string;
    /**
     * Whether the session existed and was removed.
     * @type {boolean}
     * @memberof IClearChatResponse
     */
    'cleared': boolean;
}

/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint serves as a basic connectivity test to ensure that the API is operational and accessible. It is a lightweight, read-only operation that requires no authentication or parameters.
         * @summary Ping the API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ping: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint provides information about the current version of the API. It is a lightweight, read-only operation that requires no authentication or parameters.
         * @summary Get app version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        version: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/version`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint serves as a basic connectivity test to ensure that the API is operational and accessible. It is a lightweight, read-only operation that requires no authentication or parameters.
         * @summary Ping the API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ping(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ping(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.ping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint provides information about the current version of the API. It is a lightweight, read-only operation that requires no authentication or parameters.
         * @summary Get app version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async version(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.version(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.version']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * This endpoint serves as a basic connectivity test to ensure that the API is operational and accessible. It is a lightweight, read-only operation that requires no authentication or parameters.
         * @summary Ping the API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ping(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.ping(options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint provides information about the current version of the API. It is a lightweight, read-only operation that requires no authentication or parameters.
         * @summary Get app version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        version(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.version(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI {
    /**
     * This endpoint serves as a basic connectivity test to ensure that the API is operational and accessible. It is a lightweight, read-only operation that requires no authentication or parameters.
     * @summary Ping the API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public ping(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).ping(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint provides information about the current version of the API. It is a lightweight, read-only operation that requires no authentication or parameters.
     * @summary Get app version
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public version(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).version(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ChatApi - axios parameter creator
 * @export
 */
export const ChatApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Clear one conversation session from memory
         * @summary Clear chat session
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearChat: async (sessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('clearChat', 'sessionId', sessionId)
            const localVarPath = `/chat/{sessionId}`
                .replace(`{${"sessionId"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get message from AI
         * @summary Call the AI to get message from AI
         * @param {IChatDto} iChatDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessage: async (iChatDto: IChatDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'iChatDto' is not null or undefined
            assertParamExists('getMessage', 'iChatDto', iChatDto)
            const localVarPath = `/chat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(iChatDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatApi - functional programming interface
 * @export
 */
export const ChatApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatApiAxiosParamCreator(configuration)
    return {
        /**
         * Clear one conversation session from memory
         * @summary Clear chat session
         * @param {string} sessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async clearChat(sessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IClearChatResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.clearChat(sessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.clearChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get message from AI
         * @summary Call the AI to get message from AI
         * @param {IChatDto} iChatDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessage(iChatDto: IChatDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IChatResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessage(iChatDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.getMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChatApi - factory interface
 * @export
 */
export const ChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatApiFp(configuration)
    return {
        /**
         * Clear one conversation session from memory
         * @summary Clear chat session
         * @param {ChatApiClearChatRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearChat(requestParameters: ChatApiClearChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<IClearChatResponse> {
            return localVarFp.clearChat(requestParameters.sessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get message from AI
         * @summary Call the AI to get message from AI
         * @param {ChatApiGetMessageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessage(requestParameters: ChatApiGetMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<IChatResponse> {
            return localVarFp.getMessage(requestParameters.iChatDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for clearChat operation in ChatApi.
 * @export
 * @interface ChatApiClearChatRequest
 */
export interface ChatApiClearChatRequest {
    /**
     * 
     * @type {string}
     * @memberof ChatApiClearChat
     */
    readonly sessionId: string
}

/**
 * Request parameters for getMessage operation in ChatApi.
 * @export
 * @interface ChatApiGetMessageRequest
 */
export interface ChatApiGetMessageRequest {
    /**
     * 
     * @type {IChatDto}
     * @memberof ChatApiGetMessage
     */
    readonly iChatDto: IChatDto
}

/**
 * ChatApi - object-oriented interface
 * @export
 * @class ChatApi
 * @extends {BaseAPI}
 */
export class ChatApi extends BaseAPI {
    /**
     * Clear one conversation session from memory
     * @summary Clear chat session
     * @param {ChatApiClearChatRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApi
     */
    public clearChat(requestParameters: ChatApiClearChatRequest, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).clearChat(requestParameters.sessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get message from AI
     * @summary Call the AI to get message from AI
     * @param {ChatApiGetMessageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApi
     */
    public getMessage(requestParameters: ChatApiGetMessageRequest, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).getMessage(requestParameters.iChatDto, options).then((request) => request(this.axios, this.basePath));
    }
}



